version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reconstrui
    ports: 
      - "3306:3306"
    volumes: 
      - db_data:/var/lib/mysql
    networks:
      - app-networks

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=password -connectRetries=60 migrate
    volumes: 
      - ./sql:/flyway/sql
    depends_on: 
      - db
    networks:
      - app-networks

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "3003:3003"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: reconstrui
    depends_on:
      - db
    networks: 
      - app-networks
    entrypoint: ["/wait-for-it.sh", "db:3306", "--", "npm", "start"]

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on: 
      - server
    networks:
      - app-networks

volumes:
  db_data:

networks:
  app-networks: