version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reconstrui
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  ports:
    - "3306:3306"
  volumes:
    - db_data:/var/lib/mysql
  networks:
  - app-networks      


  server:
    build:
      context: ./server
    ports:
      - "3003:3003"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: reconstrui
    depends_on:
      - db
    networks:
    - app-networks

    client:
      build:
        context: ./client
      ports:
        - 3000:80
      depends_on:
        - client
      networks:
        - app-networks

volumes:
  db_data:

networks:
  app-networks

      