FROM node:20

WORKDIR /server

COPY package*.json ./

RUN rm -rf node_modules

RUN npm install

COPY . .

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh

EXPOSE 3003

ENTRYPOINT ["/wait-for-it.sh", "db:3306", "--", "npm", "start"]